"use client"
// Auto-generated by boneyard vite plugin — do not edit
import { registerBones } from 'boneyard-js/react'

import _home_page from './home-page.bones.json'
import _page_home from './page-home.bones.json'
import _route_home from './route-home.bones.json'

registerBones({
  "home-page": _home_page,
  "page-home": _page_home,
  "route-home": _route_home,
})
